spring:
  application:
    name: demo-web
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/run
    username: root
    password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    驼峰命名开关
    map-underscore-to-camel-case: true
#更改JdbcTransactionManager日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: qzx-java-web1
    region: cn-beijing
wx:
  xcx:
    appid: wx27cb9a25c2679444
    appsecret: 345d2e5784d5ef9fb71c159193605921